spring.profiles.active=local
spring.threads.virtual.enabled=true

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.jdbc.batch_size=50

# Default values
transaction.default-category-id=6fa862ea-59e7-4d7b-8a37-d4a10a86685e

# JWT Configuration
jwt.secret=c2VjcmV0S2V5Rm9yUGVyc29uYWxGaW5hbmNlVHJhY2tlckFwcGxpY2F0aW9uT25lV2l0aEFDSUQ=

# Management
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=finance-tracker-api